import './admin-console.css';

export const adminConsoleStyles: Record<string, string> = {
  shell: 'dionysys-shell',
  header: 'dionysys-header',
  eyebrow: 'dionysys-eyebrow',
  title: 'dionysys-title',
  subtitle: 'dionysys-subtitle',
  headerActions: 'dionysys-headerActions',
  primaryButton: 'dionysys-btn dionysys-primaryButton',
  secondaryButton: 'dionysys-btn dionysys-secondaryButton',
  dangerButton: 'dionysys-btn dionysys-dangerButton',
  iconButton: 'dionysys-btn dionysys-iconButton',
  noticeBanner: 'dionysys-noticeBanner',
  errorBanner: 'dionysys-errorBanner',
  inlineError: 'dionysys-inlineError',
  layout: 'dionysys-layout',
  sidebar: 'dionysys-sidebar',
  tabButton: 'dionysys-tabButton dionysys-btn',
  activeTabButton: 'dionysys-activeTabButton dionysys-btn',
  content: 'dionysys-content',
  panelGrid: 'dionysys-panelGrid',
  metricCard: 'dionysys-metricCard',
  metricLabel: 'dionysys-metricLabel',
  metricValue: 'dionysys-metricValue',
  metricDetail: 'dionysys-metricDetail',
  card: 'dionysys-card',
  cardTitle: 'dionysys-cardTitle',
  twoColumn: 'dionysys-twoColumn',
  stack: 'dionysys-stack',
  resourceLayout: 'dionysys-resourceLayout',
  resourceList: 'dionysys-resourceList',
  resourceButton: 'dionysys-resourceButton dionysys-btn',
  activeResourceButton: 'dionysys-activeResourceButton dionysys-btn',
  resourceName: 'dionysys-resourceName',
  resourceId: 'dionysys-resourceId',
  resourceEditor: 'dionysys-resourceEditor',
  resourceChips: 'dionysys-resourceChips',
  chip: 'dionysys-chip',
  fieldGroup: 'dionysys-fieldGroup',
  label: 'dionysys-label',
  input: 'dionysys-input',
  smallInput: 'dionysys-smallInput',
  textarea: 'dionysys-textarea',
  jsonTextarea: 'dionysys-jsonTextarea',
  helpText: 'dionysys-helpText',
  noticeText: 'dionysys-noticeText',
  rowActions: 'dionysys-rowActions',
  keyValueList: 'dionysys-keyValueList',
  keyValueRow: 'dionysys-keyValueRow',
  keyLabel: 'dionysys-keyLabel',
  comparisonRows: 'dionysys-comparisonRows',
  comparisonRow: 'dionysys-comparisonRow',
  comparisonLabel: 'dionysys-comparisonLabel',
  comparisonValue: 'dionysys-comparisonValue',
  jsonBlock: 'dionysys-jsonBlock',
  table: 'dionysys-table',
  tableHeader: 'dionysys-tableHeader',
  tableRow: 'dionysys-tableRow',
  methodCode: 'dionysys-methodCode',
  pathCode: 'dionysys-pathCode',
  enabledBadge: 'dionysys-enabledBadge',
  disabledBadge: 'dionysys-disabledBadge',
  emptyState: 'dionysys-emptyState',
  emptyTitle: 'dionysys-emptyTitle',
};
