import './admin-console.css';

export const adminConsoleStyles: Record<string, string> = {
  shell: 'dionysys-shell',
  header: 'dionysys-header',
  eyebrow: 'dionysys-eyebrow',
  title: 'dionysys-title',
  subtitle: 'dionysys-subtitle',
  headerActions: 'dionysys-headerActions',
  primaryButton: 'dionysys-btn dionysys-primaryButton',
  secondaryButton: 'dionysys-btn dionysys-secondaryButton',
  dangerButton: 'dionysys-btn dionysys-dangerButton',
  iconButton: 'dionysys-btn dionysys-iconButton',
  noticeBanner: 'dionysys-noticeBanner',
  errorBanner: 'dionysys-errorBanner',
  inlineError: 'dionysys-inlineError',
  layout: 'dionysys-layout',
  content: 'dionysys-content',
  panelGrid: 'dionysys-panelGrid',
  metricCard: 'dionysys-metricCard',
  metricLabel: 'dionysys-metricLabel',
  metricValue: 'dionysys-metricValue',
  metricDetail: 'dionysys-metricDetail',
  card: 'dionysys-card',
  cardTitle: 'dionysys-cardTitle',
  twoColumn: 'dionysys-twoColumn',
  stack: 'dionysys-stack',
  sectionHeader: 'dionysys-sectionHeader',
  sectionHeaderBody: 'dionysys-sectionHeaderBody',
  sectionTitle: 'dionysys-sectionTitle',
  resourceLayout: 'dionysys-resourceLayout',
  resourceList: 'dionysys-resourceList',
  resourceButton: 'dionysys-resourceButton dionysys-btn',
  activeResourceButton: 'dionysys-activeResourceButton dionysys-btn',
  resourceName: 'dionysys-resourceName',
  resourceId: 'dionysys-resourceId',
  resourceEditor: 'dionysys-resourceEditor',
  resourceChips: 'dionysys-resourceChips',
  chip: 'dionysys-chip',
  fieldGroup: 'dionysys-fieldGroup',
  label: 'dionysys-label',
  input: 'dionysys-input',
  smallInput: 'dionysys-smallInput',
  textarea: 'dionysys-textarea',
  jsonTextarea: 'dionysys-jsonTextarea',
  helpText: 'dionysys-helpText',
  noticeText: 'dionysys-noticeText',
  rowActions: 'dionysys-rowActions',
  rangeInput: 'dionysys-rangeInput',
  compactDangerButton: 'dionysys-btn dionysys-dangerButton dionysys-compactButton',
  componentPanel: 'dionysys-componentPanel',
  componentGrid: 'dionysys-componentGrid',
  componentCard: 'dionysys-card dionysys-componentCard',
  componentCardHeader: 'dionysys-componentCardHeader',
  componentCardTitle: 'dionysys-componentCardTitle',
  componentCardId: 'dionysys-componentCardId',
  componentControlGroup: 'dionysys-componentControlGroup',
  componentControlLabel: 'dionysys-componentControlLabel',
  componentHelpText: 'dionysys-componentHelpText',
  componentDivider: 'dionysys-componentDivider',
  componentSectionTitle: 'dionysys-componentSectionTitle',
  metricHelp: 'dionysys-metricHelp',
  metricHelpPanel: 'dionysys-metricHelpPanel',
  componentMap: 'dionysys-componentMap',
  componentMapHeader: 'dionysys-componentMapHeader',
  componentMapCanvas: 'dionysys-componentMapCanvas',
  componentMapCanvasDragging: 'dionysys-componentMapCanvasDragging',
  componentMapVerticalLine: 'dionysys-componentMapVerticalLine',
  componentMapHorizontalLine: 'dionysys-componentMapHorizontalLine',
  componentMapDot: 'dionysys-componentMapDot',
  componentMapQuadrant: 'dionysys-componentMapQuadrant',
  componentMapQuadrantTL: 'dionysys-componentMapQuadrantTL',
  componentMapQuadrantTR: 'dionysys-componentMapQuadrantTR',
  componentMapQuadrantBL: 'dionysys-componentMapQuadrantBL',
  componentMapQuadrantBR: 'dionysys-componentMapQuadrantBR',
  componentMapAxisStrips: 'dionysys-componentMapAxisStrips',
  componentMapAxisStrip: 'dionysys-componentMapAxisStrip',
  componentMapAxisPole: 'dionysys-componentMapAxisPole',
  componentMapAxisArrow: 'dionysys-componentMapAxisArrow',
  componentMapCoords: 'dionysys-componentMapCoords',
  componentMapCoordGroup: 'dionysys-componentMapCoordGroup',
  componentMapCoordKey: 'dionysys-componentMapCoordKey',
  componentMapCoordVal: 'dionysys-componentMapCoordVal',
  componentMapCoordDivider: 'dionysys-componentMapCoordDivider',
  keyValueList: 'dionysys-keyValueList',
  keyValueRow: 'dionysys-keyValueRow',
  keyLabel: 'dionysys-keyLabel',
  comparisonRows: 'dionysys-comparisonRows',
  comparisonRow: 'dionysys-comparisonRow',
  comparisonLabel: 'dionysys-comparisonLabel',
  comparisonValue: 'dionysys-comparisonValue',
  jsonBlock: 'dionysys-jsonBlock',
  table: 'dionysys-table',
  tableHeader: 'dionysys-tableHeader',
  tableRow: 'dionysys-tableRow',
  methodCode: 'dionysys-methodCode',
  pathCode: 'dionysys-pathCode',
  enabledBadge: 'dionysys-enabledBadge',
  disabledBadge: 'dionysys-disabledBadge',
  emptyState: 'dionysys-emptyState',
  emptyTitle: 'dionysys-emptyTitle',
  navBar: 'dionysys-navBar',
  navTab: 'dionysys-navTab dionysys-btn',
  activeNavTab: 'dionysys-activeNavTab dionysys-btn',
  collapseBtnLeft: 'dionysys-collapseBtn dionysys-collapseBtn-left',
  collapseBtnRight: 'dionysys-collapseBtn dionysys-collapseBtn-right',
  collapsedCol: 'dionysys-collapsedCol',
};
